name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6 
  google_fonts: ^6.1.0
  curved_navigation_bar: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/myapplogo.jpg
    - assets/images/Googlelogo.jpg
    - assets/images/finallogo.jpg
    - assets/images/ditalogo.jpg

